version: '3'
services:
nginx:
    image: tutum/nginx
    ports:
        - "6666:6666"
    links:
        - phpfpm
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default

        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
    networks:
      - front-tier
      - back-tier
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
phpfpm:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./public:/usr/share/nginx/html
    networks:
      - back-tier
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: admin
  ports:
    - "3306:3306" 
  networks:
      - back-tier
  deploy:
    placement:
      constraints: [node.role == manager]
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql
  ports:
    - 6001:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: admin
    PMA_ARBITRARY: 1
  networks:
      - back-tier
  deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
  
visualizer:
  image: dockersamples/visualizer:stable
  ports:
    - "8080:8080"
  stop_grace_period: 1m30s
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   placement:
     constraints: [node.role == manager]
